<script setup lang="ts">
import StBadgeGlass from '@/components/StBadgeGlass.vue';
import StButtonGlass from '@/components/StButtonGlass.vue';
import { computed } from 'vue';

interface Props {
    mapping?: {
        change_type:
            | 'maintenance'
            | 'transformation'
            | 'enrichment'
            | 'extinction';
        required_level: number;
        current_level?: number;
        source?: 'agent' | 'manual' | 'auto';
    };
}

const props = defineProps<Props>();
defineEmits<{
    (e: 'edit'): void;
    (e: 'remove'): void;
}>();

const sourceTooltip = computed(() => {
    if (!props.mapping) return '';
    switch (props.mapping.source) {
        case 'agent':
            return 'Neural Proposal Generated by Agent';
        case 'auto':
            return 'Automatically Derived by System';
        default:
            return 'Manually Engineered Asset';
    }
});

const stateIcon = computed(() => {
    if (!props.mapping) return '';
    const icons: Record<string, string> = {
        maintenance: 'mdi-shield-check-outline',
        transformation: 'mdi-auto-fix',
        enrichment: 'mdi-trending-up',
        extinction: 'mdi-history',
    };
    return icons[props.mapping.change_type] || 'mdi-help-circle-outline';
});

const stateText = computed(() => {
    if (!props.mapping) return '';
    const texts: Record<string, string> = {
        maintenance: 'Stabilize',
        transformation: 'Evolve',
        enrichment: 'Expand',
        extinction: 'Legacy',
    };
    return texts[props.mapping.change_type] || '';
});

const stateVariant = computed(() => {
    if (!props.mapping) return 'glass';
    const variants: Record<string, string> = {
        maintenance: 'success',
        transformation: 'primary',
        enrichment: 'glass',
        extinction: 'warning',
    };
    return variants[props.mapping.change_type] || 'glass';
});
</script>

<template>
    <div
        v-if="mapping"
        class="group/cell relative flex h-full w-full flex-col items-center justify-center p-4 transition-all duration-500 hover:bg-white/[0.02]"
    >
        <!-- Top Accessory: Data Source -->
        <div
            class="absolute top-3 right-3 opacity-30 transition-all duration-500 group-hover/cell:opacity-100"
        >
            <v-tooltip :text="sourceTooltip" location="top">
                <template #activator="{ props: tooltipProps }">
                    <div
                        v-bind="tooltipProps"
                        class="flex h-6 w-6 items-center justify-center rounded-lg border border-white/5 bg-white/5"
                    >
                        <v-icon
                            size="12"
                            :color="
                                mapping.source === 'agent'
                                    ? 'indigo-300'
                                    : 'white/20'
                            "
                        >
                            {{
                                mapping.source === 'agent'
                                    ? 'mdi-brain'
                                    : 'mdi-account-edit-outline'
                            }}
                        </v-icon>
                    </div>
                </template>
            </v-tooltip>
        </div>

        <!-- Metric Visualization -->
        <div class="space-y-4 text-center">
            <StBadgeGlass
                :variant="stateVariant"
                size="sm"
                class="flex transform items-center gap-1.5 !px-3 !py-1 shadow-sm transition-transform group-hover/cell:scale-110"
            >
                <v-icon size="10" :icon="stateIcon" />
                {{ stateText }}
            </StBadgeGlass>

            <div
                class="metric-display mt-2 transition-transform duration-500 group-hover/cell:translate-y-[-2px]"
            >
                <div
                    v-if="mapping.change_type === 'transformation'"
                    class="flex items-center justify-center gap-2"
                >
                    <div class="flex flex-col items-center">
                        <span
                            class="mb-1 text-[8px] font-black tracking-widest text-white/20 uppercase"
                            >Current</span
                        >
                        <span class="text-xs font-black text-white/40">{{
                            mapping.current_level || '0'
                        }}</span>
                    </div>
                    <v-icon size="12" color="indigo-500/30" class="mt-4"
                        >mdi-chevron-right</v-icon
                    >
                    <div class="flex flex-col items-center px-2">
                        <span
                            class="mb-1 text-[8px] font-black tracking-widest text-indigo-400 uppercase"
                            >Target</span
                        >
                        <span
                            class="text-2xl leading-none font-black text-indigo-400"
                            >{{ mapping.required_level }}</span
                        >
                    </div>
                </div>
                <div v-else class="flex flex-col items-center">
                    <span
                        class="mb-1 text-[8px] font-black tracking-widest text-white/20 uppercase"
                        >Neural Req.</span
                    >
                    <span
                        class="text-3xl leading-none font-black text-white/70"
                        >{{ mapping.required_level }}</span
                    >
                </div>
            </div>
        </div>

        <!-- Interactive Overlay Layer -->
        <div
            class="absolute inset-0 z-20 flex items-center justify-center gap-3 bg-[#020617]/80 opacity-0 backdrop-blur-sm transition-all duration-500 group-hover/cell:opacity-100"
        >
            <StButtonGlass
                variant="glass"
                circle
                size="sm"
                icon="mdi-cog-outline"
                @click.stop="$emit('edit')"
            />
            <StButtonGlass
                variant="ghost"
                circle
                size="sm"
                icon="mdi-delete-outline"
                class="!text-rose-400"
                @click.stop="$emit('remove')"
            />
        </div>

        <!-- Cell Glow Foundation -->
        <div
            class="absolute -right-10 -bottom-10 h-20 w-20 rounded-full bg-indigo-500/5 opacity-0 blur-3xl transition-opacity duration-700 group-hover/cell:opacity-100"
        ></div>
    </div>

    <!-- Empty Interaction State -->
    <div
        v-else
        class="group/empty flex h-full w-full cursor-pointer items-center justify-center transition-all duration-500 hover:bg-indigo-500/[0.03]"
        @click.stop="$emit('edit')"
    >
        <div
            class="flex transform flex-col items-center gap-3 transition-all duration-700 group-hover/empty:scale-110"
        >
            <div
                class="flex h-10 w-10 items-center justify-center rounded-xl border border-white/5 bg-white/2 transition-all group-hover/empty:border-indigo-500/30 group-hover/empty:bg-indigo-500/10 group-hover/empty:text-indigo-400 group-hover/empty:shadow-[0_0_20px_rgba(99,102,241,0.1)]"
            >
                <v-icon
                    size="18"
                    class="opacity-20 transition-opacity group-hover/empty:opacity-100"
                    >mdi-plus</v-icon
                >
            </div>
            <span
                class="text-[9px] font-black tracking-[0.3em] text-white/10 uppercase transition-colors group-hover/empty:text-indigo-400/60"
                >Bridge</span
            >
        </div>
    </div>
</template>

<style scoped>
.metric-display {
    min-width: 80px;
}
</style>
