<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AssessmentCycle extends Model
{
    use HasFactory;

    protected $fillable = [
        'organization_id',
        'name',
        'description',
        'mode',
        'schedule_config',
        'scope',
        'evaluators',
        'instruments',
        'notifications',
        'status',
        'starts_at',
        'ends_at',
        'created_by',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'schedule_config' => 'array',
        'scope' => 'array',
        'evaluators' => 'array',
        'instruments' => 'array',
        'notifications' => 'array',
        'starts_at' => 'datetime',
        'ends_at' => 'datetime',
    ];

    /**
     * The organization this cycle belongs to.
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }

    /**
     * The user who created this configuration.
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * All evaluation requests generated by this cycle.
     */
    public function requests()
    {
        return $this->hasMany(AssessmentRequest::class, 'assessment_cycle_id');
    }
}
