<?php

use App\Models\LLMEvaluation;
use App\Models\Organization;
use App\Models\User;
use App\Services\RAGASEvaluator;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Http;

uses(RefreshDatabase::class);

beforeEach(function () {
    $this->organization = Organization::factory()->create();
    $this->user = User::factory()->create(['organization_id' => $this->organization->id]);
    $this->evaluator = app(RAGASEvaluator::class);

    // Mock RAGAS Python service
    Http::fake([
        'http://localhost:8001/evaluate' => Http::response([
            'faithfulness' => 0.88,
            'relevance' => 0.85,
            'context_alignment' => 0.89,
            'coherence' => 0.82,
            'hallucination' => 0.08,
            'tokens_used' => 524,
            'metric_details' => [],
            'issues' => [],
            'recommendations' => [],
        ], 200),
    ]);
});

describe('RAGASEvaluator Service', function () {
    it('creates evaluation record with pending status', function () {
        $this->actingAs($this->user);

        $evaluation = $this->evaluator->evaluate(
            inputPrompt: 'Generate a workforce plan',
            outputContent: 'Here is a detailed workforce plan...',
            organizationId: (string) $this->organization->id,
        );

        expect($evaluation->status)->toBe('pending');
        expect($evaluation->organization_id)->toBe($this->organization->id);
        expect($evaluation->created_by)->toBe($this->user->id);

        $this->assertDatabaseHas('llm_evaluations', [
            'id' => $evaluation->id,
            'status' => 'pending',
        ]);
    });

    it('supports all LLM providers (agnóstic)', function () {
        $this->actingAs($this->user);

        $providers = ['deepseek', 'abacus', 'openai', 'intel', 'mock'];

        foreach ($providers as $provider) {
            $evaluation = $this->evaluator->evaluate(
                inputPrompt: 'test',
                outputContent: "Output from $provider",
                organizationId: (string) $this->organization->id,
                provider: $provider,
            );

            expect($evaluation->llm_provider)->toBe($provider);
        }

        $this->assertDatabaseCount('llm_evaluations', 5);
    });

    it('calculates composite score from individual metrics', function () {
        $evaluation = LLMEvaluation::create([
            'organization_id' => $this->organization->id,
            'llm_provider' => 'deepseek',
            'input_content' => 'test',
            'output_content' => 'test',
            'faithfulness_score' => 0.88,
            'relevance_score' => 0.85,
            'context_alignment_score' => 0.89,
            'coherence_score' => 0.82,
            'hallucination_rate' => 0.08,
        ]);

        $composite = $evaluation->calculateCompositeScore();

        // Should be weighted average of metrics
        expect($composite)->toBeGreaterThan(0.80)->toBeLessThan(0.90);
    });

    it('normalizes score based on provider baseline', function () {
        // DeepSeek baseline: 0.82
        $evaluation_deepseek = LLMEvaluation::create([
            'organization_id' => $this->organization->id,
            'llm_provider' => 'deepseek',
            'input_content' => 'test',
            'output_content' => 'test',
            'composite_score' => 0.82,
        ]);

        // OpenAI baseline: 0.90
        $evaluation_openai = LLMEvaluation::create([
            'organization_id' => $this->organization->id,
            'llm_provider' => 'openai',
            'input_content' => 'test',
            'output_content' => 'test',
            'composite_score' => 0.90,
        ]);

        $normalized_deepseek = $evaluation_deepseek->normalizeScore();
        $normalized_openai = $evaluation_openai->normalizeScore();

        // Both at baseline should normalize to 1.0
        expect($normalized_deepseek)->toBe(1.0);
        expect($normalized_openai)->toBe(1.0);
    });

    it('determines quality level based on score thresholds', function () {
        $scores = [
            [0.95, 'excellent'],
            [0.85, 'good'],
            [0.75, 'acceptable'],
            [0.60, 'poor'],
            [0.30, 'critical'],
        ];

        foreach ($scores as [$score, $expectedLevel]) {
            $evaluation = LLMEvaluation::make([
                'composite_score' => $score,
            ]);

            $level = $evaluation->determineQualityLevel((float) $score);
            expect($level)->toBe($expectedLevel);
        }
    });

    it('detects LLM provider from output heuristically', function () {
        $this->actingAs($this->user);

        // Create evals with provider hints
        $output_deepseek = 'This was generated by deepseek model';
        $output_openai = 'GPT-4 generated response';
        $output_unknown = 'Some generic output';

        $eval1 = $this->evaluator->evaluate(
            inputPrompt: 'test',
            outputContent: $output_deepseek,
            organizationId: (string) $this->organization->id,
        );

        $eval2 = $this->evaluator->evaluate(
            inputPrompt: 'test',
            outputContent: $output_openai,
            organizationId: (string) $this->organization->id,
        );

        $eval3 = $this->evaluator->evaluate(
            inputPrompt: 'test',
            outputContent: $output_unknown,
            organizationId: (string) $this->organization->id,
        );

        // Provider detection via heuristics
        expect($eval1->llm_provider)->toBe('deepseek');
        expect($eval2->llm_provider)->toBe('openai');
        expect($eval3->llm_provider)->toBe('mock'); // Fallback to default
    });

    it('returns provider baseline score', function () {
        $baseline_deepseek = $this->evaluator->getProviderBaseline('deepseek');
        $baseline_openai = $this->evaluator->getProviderBaseline('openai');
        $baseline_mock = $this->evaluator->getProviderBaseline('mock');

        expect($baseline_deepseek)->toBe(0.82);
        expect($baseline_openai)->toBe(0.90);
        expect($baseline_mock)->toBe(0.95);
    });

    it('aggregates organization metrics', function () {
        // Create evaluations with various scores
        LLMEvaluation::factory()->create([
            'organization_id' => $this->organization->id,
            'status' => 'completed',
            'composite_score' => 0.92,
            'quality_level' => 'excellent',
            'llm_provider' => 'deepseek',
        ]);

        LLMEvaluation::factory()->create([
            'organization_id' => $this->organization->id,
            'status' => 'completed',
            'composite_score' => 0.85,
            'quality_level' => 'good',
            'llm_provider' => 'deepseek',
        ]);

        LLMEvaluation::factory()->create([
            'organization_id' => $this->organization->id,
            'status' => 'completed',
            'composite_score' => 0.78,
            'quality_level' => 'acceptable',
            'llm_provider' => 'openai',
        ]);

        $metrics = $this->evaluator->getOrganizationMetrics(
            organizationId: (string) $this->organization->id,
        );

        expect($metrics['total_evaluations'])->toBe(3);
        expect($metrics['avg_composite_score'])->toBe(0.85);
        expect($metrics['quality_distribution']['excellent'])->toBe(1);
        expect($metrics['quality_distribution']['good'])->toBe(1);
        expect($metrics['quality_distribution']['acceptable'])->toBe(1);
        expect($metrics['provider_distribution']['deepseek'])->toBe(2);
        expect($metrics['provider_distribution']['openai'])->toBe(1);
    });

    it('filters organization metrics by provider', function () {
        LLMEvaluation::factory()->count(2)->create([
            'organization_id' => $this->organization->id,
            'status' => 'completed',
            'llm_provider' => 'deepseek',
        ]);

        LLMEvaluation::factory()->create([
            'organization_id' => $this->organization->id,
            'status' => 'completed',
            'llm_provider' => 'openai',
        ]);

        $metrics_deepseek = $this->evaluator->getOrganizationMetrics(
            organizationId: (string) $this->organization->id,
            provider: 'deepseek',
        );

        expect($metrics_deepseek['total_evaluations'])->toBe(2);
        expect($metrics_deepseek['provider_distribution'])->toHaveKey('deepseek');
    });

    it('handles empty organization with no evaluations', function () {
        $metrics = $this->evaluator->getOrganizationMetrics(
            organizationId: (string) Organization::factory()->create()->id,
        );

        expect($metrics['total_evaluations'])->toBe(0);
        expect($metrics['avg_composite_score'])->toBe(0.0);
    });

    it('respects multi-tenant organization isolation', function () {
        $org1 = Organization::factory()->create();
        $org2 = Organization::factory()->create();

        LLMEvaluation::factory()->create([
            'organization_id' => $org1->id,
            'status' => 'completed',
        ]);

        LLMEvaluation::factory()->create([
            'organization_id' => $org2->id,
            'status' => 'completed',
        ]);

        $metrics_org1 = $this->evaluator->getOrganizationMetrics(
            organizationId: (string) $org1->id,
        );

        $metrics_org2 = $this->evaluator->getOrganizationMetrics(
            organizationId: (string) $org2->id,
        );

        expect($metrics_org1['total_evaluations'])->toBe(1);
        expect($metrics_org2['total_evaluations'])->toBe(1);
    });
});
